// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#ifndef RCPP_DrImpute_RCPPEXPORTS_H_GEN_
#define RCPP_DrImpute_RCPPEXPORTS_H_GEN_

#include <RcppArmadillo.h>
#include <Rcpp.h>

namespace DrImpute {

    using namespace Rcpp;

    namespace {
        void validateSignature(const char* sig) {
            Rcpp::Function require = Rcpp::Environment::base_env()["require"];
            require("DrImpute", Rcpp::Named("quietly") = true);
            typedef int(*Ptr_validate)(const char*);
            static Ptr_validate p_validate = (Ptr_validate)
                R_GetCCallable("DrImpute", "_DrImpute_RcppExport_validate");
            if (!p_validate(sig)) {
                throw Rcpp::function_not_exported(
                    "C++ function with signature '" + std::string(sig) + "' not found in DrImpute");
            }
        }
    }

    inline arma::mat imp0clC(const arma::mat X, arma::mat cls) {
        typedef SEXP(*Ptr_imp0clC)(SEXP,SEXP);
        static Ptr_imp0clC p_imp0clC = NULL;
        if (p_imp0clC == NULL) {
            validateSignature("arma::mat(*imp0clC)(const arma::mat,arma::mat)");
            p_imp0clC = (Ptr_imp0clC)R_GetCCallable("DrImpute", "_DrImpute_imp0clC");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_imp0clC(Shield<SEXP>(Rcpp::wrap(X)), Shield<SEXP>(Rcpp::wrap(cls)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<arma::mat >(rcpp_result_gen);
    }

    inline arma::mat imp0clC2(const arma::mat X, arma::mat cls) {
        typedef SEXP(*Ptr_imp0clC2)(SEXP,SEXP);
        static Ptr_imp0clC2 p_imp0clC2 = NULL;
        if (p_imp0clC2 == NULL) {
            validateSignature("arma::mat(*imp0clC2)(const arma::mat,arma::mat)");
            p_imp0clC2 = (Ptr_imp0clC2)R_GetCCallable("DrImpute", "_DrImpute_imp0clC2");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_imp0clC2(Shield<SEXP>(Rcpp::wrap(X)), Shield<SEXP>(Rcpp::wrap(cls)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<arma::mat >(rcpp_result_gen);
    }

}

#endif // RCPP_DrImpute_RCPPEXPORTS_H_GEN_
