# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title imp0clC c++ implementation to impute the zeros
#' @aliases imp0clC,DrImpute-method
#' @rdname imp0clC
#' @description impute the zeros in a single cell dataset based on a matrix and a grouping information
#' @param X the matrix of data
#' @param cls the grouping information
#' @return a matrix of expression values
imp0clC <- function(X, cls) {
    .Call('_DrImpute_imp0clC', PACKAGE = 'DrImpute', X, cls)
}

imp0clC2 <- function(X, cls) {
    .Call('_DrImpute_imp0clC2', PACKAGE = 'DrImpute', X, cls)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_DrImpute_RcppExport_registerCCallable', PACKAGE = 'DrImpute')
})
